on:
  push:
    branches: [ '*' ]
    tags-ignore:
      - v*

jobs:
  format-build-docs-and-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v8.1.0
    - uses: VirtusLab/scala-cli-setup@v1.12.5
    - name: Install verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator
    - name: Run tests
      run: scala-cli --power test .
